repos:
  - repo: local
    hooks:
      - id: tests
        name: CrunchyRest tests
        entry: ./scripts/run_crunchyrest_tests.sh
        language: system
        always_run: true
        pass_filenames: false
