repos:
  - repo: local
    hooks:
      - id: tests
        name: subset of tests
        entry: env PYTHONPATH="." python3 -m pytest CrunchyRest/test/test_founded.py CrunchyRest/test/test_industries_filter.py
        language: system
        always_run: true
        pass_filenames: false