# Generated by Django 4.1.9 on 2023-06-26 17:41

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crunchbase',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('funding', models.TextField()),
                ('website', models.URLField()),
                ('crunchbase_url', models.URLField()),
                ('logo', models.URLField()),
                ('founders', djongo.models.fields.JSONField(default=[])),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
