# Generated by Django 4.1.9 on 2023-06-27 17:48

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('databucket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crunchbase',
            name='similar_companies',
            field=djongo.models.fields.JSONField(default=[]),
        ),
    ]
