# Generated by Django 4.1.13 on 2024-09-27 07:42

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('databucket', '0002_crunchbase_similar_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedIndustries',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('industries', djongo.models.fields.JSONField(default=[])),
                ('key', models.TextField()),
            ],
        ),
    ]
