# Generated by Django 4.1.13 on 2026-02-07 17:21

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('databucket', '0003_interestedindustries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('normalized_domain', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('crunchbase_url', models.URLField(blank=True, null=True)),
                ('tracxn_url', models.URLField(blank=True, null=True)),
                ('match_confidence', models.FloatField(default=1.0)),
                ('industries', djongo.models.fields.JSONField(default=list)),
                ('similar_companies', djongo.models.fields.JSONField(default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('funding_total_usd', models.FloatField(default=0)),
                ('funding_rounds', djongo.models.fields.JSONField(default=list)),
                ('last_funding_date', models.TextField(blank=True, null=True)),
                ('last_funding_type', models.TextField(blank=True, null=True)),
                ('founders', djongo.models.fields.JSONField(default=list)),
                ('logo', models.URLField(blank=True, null=True)),
                ('founded', models.TextField(blank=True, null=True)),
                ('acquired', models.TextField(blank=True, null=True)),
                ('stocksymbol', models.TextField(blank=True, null=True)),
                ('sources', djongo.models.fields.JSONField(default=list)),
                ('source_priority', djongo.models.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveryCache',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('domain', models.TextField(unique=True)),
                ('company_name', models.TextField()),
                ('tracxn_url', models.URLField(blank=True, null=True)),
                ('searched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchQueue',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('crunchbase_id', models.TextField()),
                ('tracxn_id', models.TextField()),
                ('confidence', models.FloatField()),
                ('match_signals', djongo.models.fields.JSONField(default=dict)),
                ('status', models.TextField(default='pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TracxnRaw',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('tracxn_url', models.URLField()),
                ('website', models.URLField(blank=True, null=True)),
                ('normalized_domain', models.TextField(blank=True, null=True)),
                ('funding_total', models.TextField(blank=True, null=True)),
                ('funding_total_usd', models.FloatField(default=0)),
                ('funding_rounds', djongo.models.fields.JSONField(default=list)),
                ('founders', djongo.models.fields.JSONField(default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('founded', models.TextField(blank=True, null=True)),
                ('hq_location', models.TextField(blank=True, null=True)),
                ('matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='crunchbase',
            name='normalized_domain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='crunchbase',
            index=models.Index(fields=['normalized_domain'], name='databucket__normali_aa9e59_idx'),
        ),
        migrations.AddIndex(
            model_name='tracxnraw',
            index=models.Index(fields=['normalized_domain'], name='databucket__normali_302ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='tracxnraw',
            index=models.Index(fields=['matched'], name='databucket__matched_bd3ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='matchqueue',
            index=models.Index(fields=['status'], name='databucket__status_ecd5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='discoverycache',
            index=models.Index(fields=['domain'], name='databucket__domain_d8b81d_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['normalized_domain'], name='databucket__normali_fa6a04_idx'),
        ),
    ]
