# Generated by Django 4.1.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databucket', '0004_company_discoverycache_matchqueue_tracxnraw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crunchbase',
            name='merged_with_tracxn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracxnraw',
            name='merged_with_crunchbase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='crunchbase',
            index=models.Index(fields=['merged_with_tracxn'], name='databucket_cb_merged_tracxn_idx'),
        ),
        migrations.AddIndex(
            model_name='tracxnraw',
            index=models.Index(fields=['merged_with_crunchbase'], name='databucket_tx_merged_cb_idx'),
        ),
    ]
