# Generated by Django 4.1.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databucket', '0005_merged_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='crunchbase',
            name='tracxn_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
