# Generated by Django 4.1.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databucket', '0006_crunchbase_tracxn_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracxnraw',
            name='similar_companies',
            field=models.JSONField(default=list),
        ),
    ]
