import Head from "next/head";
import React from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'


interface Props {
  children: JSX.Element | React.ReactNode;
}

export default function Shield({ children }: Props) {
  const [queryClient] = React.useState(
    () =>
      new QueryClient({
        defaultOptions: {
          queries: {
            // With SSR, we usually want to set some default staleTime
            // above 0 to avoid refetching immediately on the client
            staleTime: 60 * 1000,
          },
        },
      }),
  )
  return (
    <QueryClientProvider client={queryClient}>
      <ToastContainer hideProgressBar newestOnTop={true} />
      <Head>
        <title>Crunchy</title>
        <meta name="description" content="Generated by Crunchy" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </QueryClientProvider>
  );
}
