import Head from "next/head";
import React from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

interface Props {
  children: JSX.Element | React.ReactNode;
}

export default function Shield({ children }: Props) {
  return (
    <>
      <ToastContainer hideProgressBar newestOnTop={true} />
      <Head>
        <title>Crunchy</title>
        <meta name="description" content="Generated by Crunchy" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
}
